# example workflow for Coverity scans using the Black Duck Security Scan Action
# https://github.com/marketplace/actions/black-duck-security-scan
name: coverity-ss-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Coverity Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: blackduck-inc/black-duck-security-scan@v2.0.0
      with:
        coverity_url: ${{ vars.COVERITY_URL }}
        coverity_user: ${{ secrets.COV_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        coverity_project_name: ccaisip-${{ github.event.repository.name }}
        coverity_stream_name: ccaisip-${{ github.event.repository.name }}-${{ github.ref_name }}
# NOTE: the testing.coverity.synopsys.com view ccaisi Outstanding Issues is set to Impact "Audit" to avoid break-build        
        coverity_policy_view: ${{ github.event_name != 'pull_request' && 'ccaisip Outstanding Issues' || '' }}
        # coverity_prComment_enabled: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # coverity_local: true
        # include_diagnostics: true
        
    - name: Coverity PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: blackduck-inc/black-duck-security-scan@v2.0.0
      with:
        coverity_url: ${{ vars.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        coverity_project_name: ${{ github.event.repository.name }}
        coverity_stream_name: ${{ github.event.repository.name }}-${{ github.base_ref }}

      ### Below configuration is used to enable feedback from Coverity security testing as pull request comment
        coverity_prComment_enabled: true
        github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when coverity_prComment_enabled is set to 'true' 
          
      # project_directory: ${{ vars.PROJECT_DIRECTORY }}  
     
     ### Uncomment below configuration if Bridge CLI diagnostic files needs to be uploaded
      # include_diagnostics: true

#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
#        include-hidden-files: true
#
# NOTE: SARIF file upload works with full analysis, not thin client
# Upload SARIF file
#    - name: Coverity SARIF Report
#      env:
#        COVERITY_URL: ${{ vars.COVERITY_URL }}
#        COV_USER: ${{ secrets.COV_USER }}
#        COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
#      run: |
#        COVERITY_TOOL_HOME=$HOME/.blackduck/bridge/tools/cov-analysis/*
#        IDIR=$(find ${{ github.workspace }}/.bridge -name idir)
#        $COVERITY_TOOL_HOME/bin/cov-format-errors --dir "$IDIR" --json-output-v10 issues.json
#        $COVERITY_TOOL_HOME/node/bin/node $COVERITY_TOOL_HOME/SARIF/cov-format-sarif-for-github.js --inputFile issues.json --outputFile results.sarif \
#          --githubUrl ${{ github.server_url }} --repoName ${{ github.repository }} --checkoutPath ${{ github.repository }} ${{ github.workspace }} ${{ github.sha }}
#    - name: Upload SARIF Report
#      uses: github/codeql-action/upload-sarif@v3
#      with:
#        sarif_file: results.sarif
